### ISSUE TITLE
[PE-D][Tester A] UG and DG naming convention

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-2/tp#197]
It might be slightly misleading to a reader when they receive a pdf with an additional AddressBook3 attached to the name rather than just KeyContacts. This is just a small suggestion to perhaps remove it.

![image.png](https://raw.githubusercontent.com/Ansel-Ch/ped/main/files/0b81c4b0-07c4-4a2b-87ee-a8c435eb1bc9.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Ansel-Ch/ped#1

**Comment by IzN432** [comment]
Take note for v1.6
