### ISSUE TITLE
[PE-D][Tester A] UG Command Overview

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-2/tp#203]
![image.png](https://raw.githubusercontent.com/Ansel-Ch/ped/main/files/6ea22fad-e6ac-41aa-bcc0-b9191fb3fb13.png)
I think for this aspect of the UG, you might have left out the `undo` command as "undo 123" is also interpreted as "undo" during my testing.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Ansel-Ch/ped#3

**Comment by IzN432** [comment]
I think this is a non-issue
