### ISSUE TITLE
[PE-D][Tester C] Able to schedule makeup lessons in the past

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-2/tp#209]
Perhaps limiting the makeup commands to future dates only could be more productive for the user since the music tutor likely doesn't want to accidentally schedule a makeup during a date that has already passed.
To reproduce: `makeup 1 dt/01-07-2020 st/12:00 et/13:00`

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: linette-g/ped#6

**Comment by dwsc37** [comment]
I think it is ok to allow archival of old makeup lessons. However, the handling of old makeup lessons to prevent interference with future actions will be covered in #256
