### ISSUE TITLE
[PE-D][Tester B] Sort by grade level does not seem to work

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-2/tp#241]
![Screenshot 2024-11-08 173728.png](https://raw.githubusercontent.com/ignatiusoey09/ped/main/files/ec47971e-95c8-4e13-9418-059be5b09141.png)

Sort grades in ascending order seems to sort by the ascii value instead of the actual grade value

Suggestion: Could consider comparing just the numerical part of the grade instead of the whole string

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ignatiusoey09/ped#8

**Comment by IzN432** [comment]
This is not counted as a bug. We should clarify this behaviour in the documentation.
