### ISSUE TITLE
[PE-D][Tester A] Assign command does not detect invalid prefixes and accepts any argument

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-2/tp#243]
![image.png](https://raw.githubusercontent.com/Ansel-Ch/ped/main/files/eeb93986-778f-48c4-8160-9e9556c2a47f.png)
As a tutor that might be unfamiliar with the product, I might add some additional prefixes for the assign command such as a date to indicate that they would like to introduce that piece on a certain date.

![image.png](https://raw.githubusercontent.com/Ansel-Ch/ped/main/files/e9f352f1-3e06-43b9-b683-6f70aa013024.png)

![image.png](https://raw.githubusercontent.com/Ansel-Ch/ped/main/files/c4bc973c-28a6-4bb0-a85c-9c1d3ce54ef3.png)

This was the outcome. Perhaps there should be better regex in place to detect for these situations as It appears pn/ prefix accepts any input given to it, even if it is just symbols like in the second image.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Ansel-Ch/ped#10

**Comment by IzN432** [comment]
This is intended to allow for piece names with slashes in them.
