### ISSUE TITLE
[PE-D][Tester D] Table of Contents in user guide missing labelling

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-2/tp#253]
In the user guide, it's hard to understand the flow of the sections without proper numbering of the table of contents

![image.png](https://raw.githubusercontent.com/rithanisk/ped/main/files/cf823730-6790-4bb5-8db1-6817fbb42814.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: rithanisk/ped#13

**Comment by IzN432** [comment]
I don't understand this. Anyone have any opinions?

**Comment by dwsc37** [comment]
Don't think its an issue, the indentations are clear.
